### ISSUE TITLE
Can't get a client Object

### ISSUE THREAD

**Issue by jackdorson** [GemHQ/round-node#5]
Hello,
I am no expert at node.js but I am trying to build Bitcoin app and want to integrate wallets. I use 

var Round = require("round-node");
Round.client(options, callback);

but i am not getting a client object returned. Instead I am getting a promise object return but there are no methods client.authenticateIdentify etc.

What am i doing wrong?

**Comment by bezreyhan** [comment]
@jackdorson the Readme and docs need some updating. We are no longer using callback but are using Promises instead.

You should be able to do
```
var Round = require("round-node");
Round.client()
.then(function(client) {
   console.log(client);
});
```

I'll spend some time updating the docs and Readme today and tomorrow.

This gist is also outdated because it uses callbacks and not promises, but nevertheless it should help you get started with the Node client: https://gist.github.com/bezreyhan/a7190a6c0e9fe592daa8

Let me know if you have any other questions.

**Comment by jackdorson** [comment]
I see. Do you think you can provide me with a quick example on how I can authenticate a client? Sorry i can't seem to figure it out

**Comment by bezreyhan** [comment]
Sure, I'll work on that and get back to you as soon as it's finished.

**Comment by bezreyhan** [comment]
@jackdorson I just updated the node client so your going to want to update to version 0.3.1

Here is the updated code snippet which uses promises. The example will take you through a general overview of the api: https://gist.github.com/bezreyhan/a7190a6c0e9fe592daa8

Let me know how that works out for you.

**Comment by jackdorson** [comment]
Hey thanks so much. This really helps.

Just wondering, I wanna check if a user already has a gem account. So I am doing 

Round.client()

.then(function (client) { client.authenticate_identify({api_token : APITOKEN});															return client.user(email); }).then(function (user) { console.log(user);  });

But i keep getting this message:

{ [Error: Unexpected response status: 405]
  cause: 
   { [Error: Unexpected response status: 405]
     status: 405,
     response: 
      { raw: [Object],
        _content: [Object],
        status: 405,
        headers: [Object],
        _normalized: [Object],
        content: [Object],
        body: '{"status":405,"message":"Method Not Allowed"}',
        data: undefined } },
  isOperational: true,
  status: 405,
  response: 
   { raw: 
      { _readableState: [Object],
        readable: false,
        domain: null,
        _events: [Object],
        _maxListeners: undefined,
        socket: [Object],
        connection: [Object],
        httpVersionMajor: 1,
        httpVersionMinor: 1,
        httpVersion: '1.1',
        complete: true,
        headers: [Object],
        rawHeaders: [Object],
        trailers: {},
        rawTrailers: [],
        _pendings: [],
        _pendingIndex: 0,
        upgrade: false,
        url: '',
        method: null,
        statusCode: 405,
        statusMessage: 'Method Not Allowed',
        client: [Object],
        _consuming: true,
        _dumped: false,
        req: [Object],
        read: [Function] },
     _content: 
      { response: [Circular],
        raw: [Object],
        chunks: [Object],
        length: 45,
        type: undefined,
        encoding: null,
        buffer: <Buffer 7b 22 73 74 61 74 75 73 22 3a 34 30 35 2c 22 6d 65 73 73 61 67 65 22 3a 22 4d 65 74 68 6f 64 20 4e 6f 74 20 41 6c 6c 6f 77 65 64 22 7d>,
        body: '{"status":405,"message":"Method Not Allowed"}' },
     status: 405,
     headers: 
      { date: 'Thu, 02 Jul 2015 15:29:44 GMT',
        vary: 'Accept-Encoding',
        'content-length': '45',
        connection: 'Close' },
     _normalized: 
      { Date: 'Thu, 02 Jul 2015 15:29:44 GMT',
        Vary: 'Accept-Encoding',
        'Content-Length': '45',
        Connection: 'Close' },
     content: 
      { buffer: <Buffer 7b 22 73 74 61 74 75 73 22 3a 34 30 35 2c 22 6d 65 73 73 61 67 65 22 3a 22 4d 65 74 68 6f 64 20 4e 6f 74 20 41 6c 6c 6f 77 65 64 22 7d>,
        body: '{"status":405,"message":"Method Not Allowed"}',
        data: undefined },
     body: '{"status":405,"message":"Method Not Allowed"}',
     data: undefined } }

**Comment by bezreyhan** [comment]
@jackdorson I need to look into this. Though, the reason why your getting this particular error is because you ran:
`client.user(email); `
as apposed to:
`client.user({email: 'USER_EMAIL'});`

For future reference, all methods take object. However, you may hit other issues. I'm gonna test out the Node client right now and push changes if need be. I'll get back to your shortly.

**Comment by bezreyhan** [comment]
@jackdorson sorry for the delay. I just pushed up some new code to github and and pushed v.3.2 to npm

Though, running `client.user` will not tell you if a user exists. You can simply try to create a user via `users.create` and if you get a `409 conflict error ` then you'll know that the user exists in the Gem system.

If you wan to authenticate a user you have to run `authenticate_device({api_token, device_token, email})` . The email is the users email. The device_token is received after creating a user. Alternatively, you can get the device_token by running `devices.create({name, redirect_uri})`. You can get `devices` by running `user.devices()`

**Comment by jackdorson** [comment]
Thanks so much. You were a big help. Can't wait to start playing around
with the API more

**Comment by joshua-bv** [comment]
hey @jackdorson I'm going to close this ticket out - reopen or file a new one with any issues or questions you might have.  Also don't forget to sign up for our slack support team via the badge in the READ.ME
